### ISSUE TITLE
Missing BIS Corrective Invoice in PeppolDocumentTypeIdAcronym.java

### ISSUE THREAD

**Issue by senikk** [OxalisCommunity/oxalis#16]
When you add "Standalone Credit Note according to EHF" in ELMA Web Interface you also get some additional document types and one of those like BIS Correcitve Invoice:

urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:www.cenbii.eu:transaction:biicoretrdm015:ver1.0:#urn:www.peppol.eu:bis:peppol5a:ver1.0::2.0

But this one doesn't exist in PeppolDocumentTypeIdAcronym.java

We have received some of those type of documents on our accesspoint so I just checked this part of Oxalis.

**Comment by VijayaKumar2** [comment]
We are also managing with Custom Acronym only for various document identifiers, because the read participant from SMP is not giving the SMP document id, so we are also depending on the document identifier (Acronym only).

If SMP Response of the single participant response returns the document id also, means we can relay on that for comparing the document type.
 
Please do share the document which you have mentioned above.
